### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/qupath-extension-biop-hrm#1]
Hi @Rdornier ,

Having a progress during transfer of data would be nice 😁 

Bonus : the window gives the location of the transferred data as a "selection-able" text, so I can copy and paste it into explorer to get to the data 🤓

Cheers,

R

**Comment by Rdornier** [comment]
Hi @romainGuiet,
Nice feature. I'be impemented it for the next release

**Comment by Rdornier** [comment]
Integrated from b4f99b7ce70f3b21a40b1ee7909a21feffa955be
